branch-defaults:
  master:
    environment: Minehaus-env
    group_suffix: null
global:
  application_name: minehaus
  branch: null
  default_ec2_keyname: minehaus
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: minehaus
  repository: null
  sc: git
  workspace_type: Application
